{{- if .Values.grafanaAdminSealedSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.grafanaAdminSealedSecret.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: monitoring
spec:
  encryptedData:
    admin-user: {{ required "grafanaAdminSealedSecret.encryptedData.admin-user is required" (index .Values.grafanaAdminSealedSecret.encryptedData "admin-user") | quote }}
    admin-password: {{ required "grafanaAdminSealedSecret.encryptedData.admin-password is required" (index .Values.grafanaAdminSealedSecret.encryptedData "admin-password") | quote }}
  template:
    metadata:
      name: {{ .Values.grafanaAdminSealedSecret.name }}
      namespace: {{ .Release.Namespace }}
{{- end }}

