apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: accounts

resources:
  - ../../base
  - accounts-ingress.yaml
  - postgres-sealedsecret.yaml
  - accounts-servicemonitor.yaml
  - namespace.yaml
  - postgres-pvc.yaml

patches:
  - path: postgres-storage-patch.yaml

images:
  - name: ghcr.io/jeremyrc760/devops-capstone-project
    newTag: sha-fd6a3e1