apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/part-of: devops-capstone
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-gp3
  resources:
    requests:
      storage: 10Gi