apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-grafana-alerting
  namespace: {{ .Release.Namespace }}
  labels:
    grafana_alert: "1"
    app.kubernetes.io/part-of: monitoring
data:
  alert-rules.yaml: |-
{{ .Files.Get "provisioning/alert-rules.yaml" | indent 4 }}
  contact-points.yaml: |-
{{ .Files.Get "provisioning/contact-points.yaml" | indent 4 }}
