---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prometheus-basic-auth
  namespace: monitoring
spec:
  encryptedData:
    auth: AgBmgdsBpofEhKY2BLBXu7aZk9Sthk6MCASZYHBrrp3XUT7ns/d32nuiFmXXAlzuMtrz7VCGafM/Peafl34UgovyyKKM7KVQcSbuqCWtVhdvu6Jm8WZXl3QZBR+IWob2HdYRiG7sY75KF1hKAyVDmmVZ9x5mluPbC4cnEn9dGg0C2nAm0COpj4pUphETyjA29p0SW92IP8EguEkvbARiUuZ7FAQqcHo6g86vpxSnmD3U5rwQ6gGiLPIWTEU1qpRI79k/o+8hugLyEcGqPdcHFMlU09HqNNGqTrN+Lj0SFxFYqGR4VoJxeSdBMTZK803o7mS3pXjRleyYgWfFjirQaJxgaifa/egtXd8D5+0MTW60kHSTsaUozQQVmLdCq69lDdtHJFmGG3743GIRf6zTBWcCPvpaGf09uwTe0WeRVJ7Eu5Hbayo8/k19IkFOMpDozAYSCsGQyJeplQ/oqfv6UBediNUSr7PYefIeA7AiKo+wYKwJDjE6GZl2430hlZUU+n7GWNFuShrFaCR4LKgUcFBUqN15cNQmTAmh/Brbyx+XqOQ/SjgBqaF4EKhBNVHAGjPhA0R+8+3/C73w8J6ksQVg6MKdcOP3M7Ii91vk9j7qSGKMdoB/NMe++h3LuibpvYBJTchJ2NtPx/e+0YcMAenWWOzBk2DtsV+uZzPYJ4mRR1yiVNW+xFEf+9q/1s7EK8ytJqvVA741KuJF30F0HQsHT8M66+3eGolBCQR/pdzogQ41EuHi55IPUnX+NtJjNVNd
  template:
    metadata:
      name: prometheus-basic-auth
      namespace: monitoring
    type: Opaque
