{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: accounts
  namespace: {{ include "accounts.namespace" . }}
  labels:
    {{- include "accounts.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "accounts.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/part-of: devops-capstone
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.interval }}
      scrapeTimeout: {{ .Values.monitoring.scrapeTimeout }}
{{- end }}
