{{- if .Values.postgresql.sealedSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql
  namespace: {{ include "accounts.namespace" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  encryptedData:
    database-name: {{ required "postgresql.sealedSecret.encryptedData.database-name is required" (index .Values.postgresql.sealedSecret.encryptedData "database-name") | quote }}
    database-user: {{ required "postgresql.sealedSecret.encryptedData.database-user is required" (index .Values.postgresql.sealedSecret.encryptedData "database-user") | quote }}
    database-password: {{ required "postgresql.sealedSecret.encryptedData.database-password is required" (index .Values.postgresql.sealedSecret.encryptedData "database-password") | quote }}
  template:
    metadata:
      name: postgresql
      namespace: {{ include "accounts.namespace" . }}
{{- end }}
