namespace:
  create: false
  name: accounts-helm-dev

accounts:
  replicaCount: 1
  service:
    type: ClusterIP
    nodePort: null

postgresql:
  sealedSecret:
    enabled: true
    encryptedData:
      database-name: AgAXLsPtVh+Mgk38eNDfgRp4GUTwW22g+jCRY5DbH9m0PMmNcQ8Ihy3hdokdyNdyKiqAzA/lJWDT93uzLaucQuTvzSrCBIA7ly5vQvHa2S3eYSp5KZX3pj9vvNgKGypm5uF2OCmftHH3wihWkI8MC1W3Qg4PAO8xIlYc8PtgtbkItbXmNF6Lxy6WBp1iphP8T9Y/3wswnd4cgKoZSQlZZ3WKfCDr6mqU73YGnSeYCguakhJO5aVtHM8CbP3POAazVBdYZNrX3Hw3CrZHhvfK7W9av35G2gyLQ4OAT2uswbJYVTqXe6shVHQ6Ce3jcQxeilhAnWTnS9XxCIJHu/chBIveJyuSZOy9XPW6kPTxybm5AZqT93WuMJ1ydb+BkSn0jg09iTqyrA/i7ulZAoN7CdfqRHbisTkNrxaMNPCK+ceUSBmeJU13TwxcjBsdnnaYgz9L887tMxIi8/TJokeKc7T5CTXQcDn+WLGNHjnlYDXNso4zm5S3wP+uNdMGidUxyRRjR6hETwMBFrSd+SCOL9wIhpToG3JMG53mCB50UYJK7xLU+cuUV2qE4ul1I3rKlItlLUkBodmLlPaQlLACD2uShaYLatjN1fv2vkaJkfQ20cnpFQnB/n9Jev+qWTVE3bysmuq5kSFw+EUzzcBc8X3Hjo+jz947940pPvsXRfy/RUf1Dp7XzgCqYWf1xojkjHegGe6mF/2nuQ==
      database-user: AgBbh7c1gUK5mS1Qo/0Dxa10L7h5We6xkgr6Q/t2nMxROoWOf0zDpCEJEHrQRuR0oXN+HE1aZrmeI4leTKeKbqoQjR3P0Sf0NmjsMEpCnW55Gph9/hrpiKQYWua4I7fYGUdc+faWLCrvuCa9LTmg9oUswXSi+PD9pgWnlXk1B/NgvvgSr60+OkuoO5KKE2JgN6S86caonIEpY1iO9jnwGS7p5I/m/l2dqYHzHZgK+BWUTPU33H3Y+ujca8R09dBBGOz3QHftsoIlQzbGjh3Mb2XK+gZrv87pljZ37WnRTxNshrks3yZA+05D5WHqxRc74iH8CgnV4Id97OQRJLxZmZiZFSzP1WdF+XCMpeaCRVvgUVnyQX3LKEcBhSmMRFGBGN1/2ztrJ7TprEcjcwEftBZNfaYLGSATqugGQFAcnGg40JLzkP8VV0TzyfLHAzbB64dxfo6AcejCg0zCIQqb8zL31L6/Z/fFENyZIRoccexKCfv0pJkKoA5YyioXvFJPubmhYaIz8eu5crVwXbdOJWKBNGK4cD7GTdDYRL5ytyuDijCQd/lvtbrgdZae8h7pThkjCcL6CeQkE7x0lY71XgHbO4lCVxPGbkbeUJPrKlEf5TacB56xSEHFjkiN+OOT7UDtB1Aqb/pG7kP2qX0HRIF4EJ2GZKy+Trlh5GdALQcM5Qgg1YIVdHRn64hsm93sNOXEXbr7wv7zWA==
      database-password: AgCjgYfK78tHu9Gn52Op/4ZxTUXQDRXExbkCzaFFvM+jf3o4pNlMIbyk+krXkJEJPsNZi+RcJHmwTMbMOutDNNZsw32y1gOUwAv6Yd47kHfe3pGdTisQYtL3CbmElgJInR5Da4HVJzsKn/8JfzgDUehw9+WYMoITZP32NEyhuTri0blxvIlnx9iX0ovtpJhvgAvcB7YSFgHXs4cTaCiEW6+3nqC2JZiZ47bBQZsn9sgAvPhbZbDvort7p4xI1jhOWPkkjlffpsLXDUIKUQpycLUCIbqUrfKy5JyaAin2r+UmFBUw19FC+KFwxCRYX2nhWmQf77s04+iockNZVePj304kX0wrhdpD2dyWrmwZYm42Uyfy1GeQLOOZN7MMGg/+YsOdEMemLOy6srqItyiLSlJQMG7+UXRd33/ZA4+mtLsUbQKvbA1JsyRwT7K+zahOpXQ8RQdBQMkTFLotnp9X5x7E7RNnRpMuPKcfgXkpMgBpAGIQMCr/+G08BJQpBYK0f1+f1l1vsdRZQuxt0kQB0jtNe1k7JC8+FwfgAx/rp0HbTZB+wzHafD2OldJ9iekYiYZrboXRwlFkDqHpOjirb/e5pyaDBnTjuzQF2PY1mqup6E/wcfW52MleVGQ/V73mMC+ZKeXRbUKDIn1MJeC4+2X8VhRQuPNqqIndtSjxukvMvTVsKDYlgcOl/btGql943ucJZOn0Sowqdw==

ingress:
  enabled: false
