apiVersion: v1
kind: ConfigMap
metadata:
  name: accounts-config
  namespace: accounts
  labels:
    app.kubernetes.io/name: accounts
    app.kubernetes.io/part-of: devops-capstone
data:
  DATABASE_HOST: postgresql
  FORCE_HTTPS: "false"
