apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  namespace: accounts
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/part-of: devops-capstone
type: Opaque
stringData:
  database-name: CHANGE_ME_DATABASE_NAME
  database-user: CHANGE_ME_DATABASE_USER
  database-password: CHANGE_ME_DATABASE_PASSWORD
